#ifndef __1__
#define __1__

#define LALR2C_TOKENS \
    LALR2C_TOKEN(T_ALT) \
    LALR2C_TOKEN(T_ASSERT) \
    LALR2C_TOKEN(T_ASSERT_FOLLOW) \
    LALR2C_TOKEN(T_ASSERT_FOLLOW_NOT) \
    LALR2C_TOKEN(T_BACKREF) \
    LALR2C_TOKEN(T_CAPTURE_END) \
    LALR2C_TOKEN(T_CAPTURE_START) \
    LALR2C_TOKEN(T_CAPTURE_START_LAZY) \
    LALR2C_TOKEN(T_CLASS) \
    LALR2C_TOKEN(T_CLASS_END) \
    LALR2C_TOKEN(T_CLASS_START) \
    LALR2C_TOKEN(T_CLASS_START_NEG) \
    LALR2C_TOKEN(T_COUNTED_REPEAT) \
    LALR2C_TOKEN(T_DASH) \
    LALR2C_TOKEN(T_DOT) \
    LALR2C_TOKEN(T_LBRACE) \
    LALR2C_TOKEN(T_LBRACE_LAZY) \
    LALR2C_TOKEN(T_ONE_MANY) \
    LALR2C_TOKEN(T_RBRACE) \
    LALR2C_TOKEN(T_RUNE) \
    LALR2C_TOKEN(T_TIMES) \
    LALR2C_TOKEN(T_TIMES_FROM) \
    LALR2C_TOKEN(T_TIMES_FROM_TO) \
    LALR2C_TOKEN(T_ZERO_MANY) \
    LALR2C_TOKEN(T_ZERO_ONE) \
    LALR2C_TOKEN(T_LAMBDA) \

#endif // __1__