#ifndef __1__
#define __1__

#define LALR2C_TOKENS \
    LALR2C_TOKEN(T_ALT) \
    LALR2C_TOKEN(T_ASSERT_START) \
    LALR2C_TOKEN(T_ASSERT_END) \
    LALR2C_TOKEN(T_ASSERT_WORD) \
    LALR2C_TOKEN(T_ASSERT_FOLLOW) \
    LALR2C_TOKEN(T_BACKREF) \
    LALR2C_TOKEN(T_CLASS) \
    LALR2C_TOKEN(T_CLASS_END) \
    LALR2C_TOKEN(T_CLASS_START) \
    LALR2C_TOKEN(T_COMMA) \
    LALR2C_TOKEN(T_DASH) \
    LALR2C_TOKEN(T_DOT) \
    LALR2C_TOKEN(T_LBRACE_CAPTURE) \
    LALR2C_TOKEN(T_LBRACE_LAZY) \
    LALR2C_TOKEN(T_NUMBER) \
    LALR2C_TOKEN(T_ONE_MANY) \
    LALR2C_TOKEN(T_RBRACE) \
    LALR2C_TOKEN(T_RUNE) \
    LALR2C_TOKEN(T_ZERO_MANY) \
    LALR2C_TOKEN(T_ZERO_ONE) \
    LALR2C_TOKEN(T_LAMBDA) \

#endif // __1__