#ifndef __1__
#define __1__

#define LALR2C_TOKENS \
    LALR2C_TOKEN(ALT) \
    LALR2C_TOKEN(ASSERT_END) \
    LALR2C_TOKEN(ASSERT_START) \
    LALR2C_TOKEN(CHAR) \
    LALR2C_TOKEN(CLASS) \
    LALR2C_TOKEN(COUNTED_REPEAT) \
    LALR2C_TOKEN(DOT) \
    LALR2C_TOKEN(ESC_CLASS) \
    LALR2C_TOKEN(ESC_CONLROL) \
    LALR2C_TOKEN(ESC_CONTROL_LETTER) \
    LALR2C_TOKEN(ESC_HEX) \
    LALR2C_TOKEN(ESC_IDENTITY) \
    LALR2C_TOKEN(ESC_INTEGER) \
    LALR2C_TOKEN(ESC_UNICODE) \
    LALR2C_TOKEN(ESC_WORD_LOWER) \
    LALR2C_TOKEN(ESC_WORD_UPPER) \
    LALR2C_TOKEN(LBRACE) \
    LALR2C_TOKEN(LBRACE_ASSERT_NO) \
    LALR2C_TOKEN(LBRACE_ASSERT_YES) \
    LALR2C_TOKEN(LBRACE_LAZY) \
    LALR2C_TOKEN(ONE_MANY) \
    LALR2C_TOKEN(RBRACE) \
    LALR2C_TOKEN(ZERO_MANY) \
    LALR2C_TOKEN(ZERO_ONE) \
    LALR2C_TOKEN(LAMBDA) \

#endif // __1__